### PR TITLE
Use new __traits(isZeroInit) to check for a null initializer at compile time instead of runtime

### PR DESCRIPTION
**Pull request by n8sh**
As done in https://github.com/dlang/phobos/pull/6698 and https://github.com/dlang/phobos/pull/6461.

### CODE REVIEW

**Comment by n8sh** [comment]
This PR requires features from [DMD 2.083.0](https://dlang.org/changelog/2.083.0.html) so it doesn't work on the auto-tester yet.

**Comment by belka-ew** [comment]
@n8sh the PR actually looks good, fill free to reopen it, but I can't merge it currently, since I build my production code with the latest GDC and it is currently on 2.081.2. But I would merge it as soon as I update the compiler. You can also use `__VERSION__` if you want.

**Comment by n8sh** [comment]
Updated to use `__VERSION__` to work with pre-2.083 compilers.

**Comment by belka-ew** [comment]
Merged, thanks!

**Comment by belka-ew** [comment]
Merged, thanks!

**Comment by belka-ew** [comment]
Merged, thanks!

**Pull request merged**
